trickstercache/trickster

- docs/health.md
changed it's to its 
it's = it is and didn't make sense
> minor change copy/editing

- deploy/README.md
- deploy/helm/Makefile
Update:
Kubectl version to latest supported by minikube
Helm + tiller version to latest
Tested working locally
> update kubectl, minikube, helm to latest supported versions

- handlers.go
> nil check response to avoid SIGSEGV on failure

- conf/example.conf
- config.go
- main.go
- metrics.go
Closes #25 
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Allow listening on specific IP addresses

- docs/multi-origin.md
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Fix multi origin doc

- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/README.md
- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
Templatized more of the config map so that users aren't restricted to default configurations.
Also upped the default docker image version and chart version.
> Expose more config params to be set through helm values.

- handlers.go
Use Go `time.Duration` type for handling time obersvations.
Signed-off-by: Ben Kochie <superq@gmail.com>
> Use time.Duration()

- Makefile
- filesystem_test.go
- flags_test.go
- handlers_test.go
- logging_test.go
- memory.go
- memory_test.go
- redis.go
- redis_test.go
Add unit tests for #1. This set of tests increases the coverage to 48.5%.
> Add unit tests

- .travis.yml
- Makefile
- filesystem_test.go
- flags_test.go
- handlers_test.go
- logging_test.go
- memory_test.go
- redis_test.go
* Add a `style` make target.
* Run tests in travis.
* `go fmt`.
> Cleanup style

- .travis.yml
- conf/example.conf
- deploy/README.md
- handlers.go
* Fix spelling issues.
* Add codespell to travis.
Update example.conf
* Simplify indenting.
* Fix some minor spacing issues.
> Minor cleanup

- handlers.go
Fixes https://github.com/Comcast/trickster/issues/74
> Allow non-int formats for "step" value

- .gitignore
- .travis.yml
- Gopkg.lock
- Gopkg.toml
- Makefile
* Run all tests in Travis.
* Use `dep ensure` to install deps.
* Update deps.
* Misc Makefile cleanup.
Closes: https://github.com/Comcast/trickster/issues/75
> Add test to build pipeline

- handlers.go
This is a short-term workaround for #82 as the "correct" fix will take some time, but this fixes it *now*.
> Workaround to handle scalar responses

- handlers.go
Signed-off-by: Arsen Akishev <arsenakishev@gmail.com>
> Change real-time request test to use ctx.Time in milliseconds

- Gopkg.lock
- Gopkg.toml
- MAINTAINERS.md
- boltdb.go
- boltdb_test.go
- cache.go
- conf/example.conf
- config.go
- docs/caches.md
- filesystem.go
- main.go
- redis.go
- redis_test.go
> BoltDb Cache Support

- handlers.go
- handlers_test.go
the current implementation of mergeMatrix assumes that `pe2` is "before"
`pe`-- but does not thing to actually ensure or enforce that this is the
case. This means if there is overlap we can get dupe points. For
example (with the test case in the PR):
```
--- FAIL: TestTricksterHandler_mergeMatrix (0.00s)
--- FAIL: TestTricksterHandler_mergeMatrix/0 (0.00s)
handlers_test.go:542: Mismatch
actual={success {matrix a =>
1.5 @[0.001]
1.5 @[0.002]
1.5 @[0.001]}}
expected={success {matrix a =>
1.5 @[0.001]
1.5 @[0.002]}}
```
This is likely the cause for a variety of "dupe points" or other
out-of-order points problems.
This change still assumes that the 2 series are "in order", if we wanted to not rely on that at all we'd need a more complete merging/sorting implementation like that in …
> Validate ordering assumption in mergeMatrix

- handlers.go
In the use, I find the max_value_age_secs works both on cache and data returned to user. I set the max_value_age_secs to 86400(1day), and I use Grafana to query for 7 days' data, Trickster will only return 1 day's data to Grafana. I think maybe the max_value_age_secs should only works on cached data, not crop the data return to user, so I push a pull merge request, I don't know is this ok for this question.
> fix the max_value_age_secs works on data return to user.

- conf/example.conf
- config.go
- handlers.go
- handlers_test.go
> Add per-origin upstream timeout

- Makefile
- deploy/Dockerfile
This simply updates the main Makefile and Dockerfile to follow along with the new directory structure.
> Fix makefile

- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
- deploy/kube/configmap.yaml
I suppose I could PR onto the PR this relates to.
This PR follows the config updates present in #164, and should only be merged **After** 164 is merged.
#164 and this do not touch any of the same file and there should be no conflicts.
> Update configmaps to follow new config layout

- internal/proxy/deltaproxycache.go
- internal/proxy/influxdb/key.go
- internal/proxy/objectproxycache.go
- internal/proxy/prometheus/key.go
- internal/proxy/request.go
> 1.0 header panics

- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
- deploy/kube/configmap.yaml
- go.mod
- go.sum
- internal/cache/badger/badger.go
- internal/cache/badger/badger_test.go
- internal/cache/registration/registration.go
- internal/config/config.go
Add support for badger key-value store -- its supposed to have some performance improvements over bolt.
https://github.com/dgraph-io/badger
> Badger kv cache support

- deploy/helm/trickster/templates/configmap.yaml
Two minor issues noticed by @crandles.
> Config fix

- docs/caches.md
- internal/cache/badger/badger.go
> observe Badger cache metrics

- internal/proxy/headers.go
- internal/proxy/proxy.go
> 1.0 - Move Resp Headers to func and add CORS from 0.1.x

- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/README.md
- deploy/helm/trickster/templates/NOTES.txt
- deploy/helm/trickster/templates/_helpers.tpl
- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/templates/deployment.yaml
- deploy/helm/trickster/templates/ingress.yaml
- deploy/helm/trickster/templates/pvc.yaml
- deploy/helm/trickster/templates/service.yaml
- deploy/helm/trickster/values.yaml
> Update helm chart example

- handlers.go
The old behavior would query from the end of the requested data until
the beginning of the cached data. So as an example, if you did a query for the last 30m and then did a query for a 30m window a month ago-- that second query would attempt to fetch all data from a month ago until now-- which isn't what we want (and in practice it fails).
This instead changes the end of the query range to be the normalized end
of the query-range
Fixes #131
> More conservative data fetching for partial cache hit

- handlers.go
Fixes the regression added in #196 
cc @jranson once this is merged, can we cut a release of the 0.x series?
> Properly set Content-Type

- internal/proxy/engines/client_test.go
- internal/proxy/engines/deltaproxycache.go
- internal/proxy/origins/influxdb/series.go
- internal/proxy/origins/prometheus/handler_health.go
- internal/proxy/origins/prometheus/matrix.go
- internal/proxy/origins/prometheus/matrix_test.go
- pkg/promsim/http_server.go
fixes #237
fixes #238
adds minor promsim update for rfc3399 times
> 1.0 - Fix Prom Panic and Cache Empty Sets

- README.md
Add swarmstack to the list of Trickster users.
> Add swarmstack to "users of Trickster"

- cmd/trickster/main.go
- internal/config/config.go
- internal/config/loader.go
- internal/config/loader_test.go
- testdata/test.full.conf
- testdata/test.warning1.conf
- testdata/test.warning2.conf
> add redis warnings

- cmd/trickster/conf/example.conf
- deploy/helm/Makefile
- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/README.md
- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
- deploy/kube/configmap.yaml
Intentions:
- Update the configmaps and documentation for kube/helm deployments
- Minor example config consistency fix
- Make the helm charts look more like the Prometheus charts
> Update config maps to reflect new example config.

- internal/proxy/engines/deltaproxycache.go
> Fix small typo

- README.md
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>
> Add Hostinger as an existing user of trickster

- conf/example.conf
- config.go
- main.go
#285 
I added TLS setting in trickster.config
> Support TLS #285

- cmd/trickster/conf/example.conf
- docs/negative-caching.md
- docs/new-changed-1.0.md
- internal/proxy/engines/objectproxycache_test.go
feature has already been implemented but lacked docs and a functional test
> 1.0 negative cache docs

- cmd/trickster/conf/example.conf
- docs/paths.md
- internal/proxy/origins/reverseproxycache/routes.go
- internal/routing/registration/registration.go
- testdata/test.multiple_origins.conf
> 1.0 wc method path

- internal/proxy/engines/progressive_collapse_forwarder.go
- internal/proxy/engines/progressive_collapse_forwarder_test.go
Add benchmarks for Progressive Collapse Forwarder Read/Write methods.
> Add pcf benchmarks

- internal/cache/redis/client_types.go
- internal/cache/redis/redis.go
- internal/proxy/engines/proxy_request.go
addresses panic on cache miss when using redis cache, other minor improvements
> Redis improvements

- internal/proxy/engines/httpproxy.go
> remove host header before proxying

- cmd/trickster/main.go
- internal/routing/registration/registration.go
This PR updates the output formatting and scope of startup log entries such that they are more user-friendly, descriptive, and assistive in troubleshooting. It does not have any functional change.
> startup aesthetics

- internal/config/config.go
- internal/config/defaults.go
- internal/config/flags.go
- internal/config/loader.go
- internal/config/loader_test.go
this removes the global state for flags, adds some additional tests, and does other minor cleanup.
> remove global state from flags

- internal/config/loader_test.go
- internal/config/tls.go
- internal/proxy/proxy_test.go
also fixes some tests that fail between go 1.13 and go 1.14
> add frontend HTTP 2.0 support

- internal/proxy/engines/key.go
- internal/proxy/origins/prometheus/prometheus.go
- internal/proxy/origins/prometheus/url.go
> support prometheus POST queries

- internal/cache/filesystem/filesystem.go
> fix filesystem hang on bulk remove

- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/templates/configmap.yaml
Wrong indentation for tracing section.
> Fix indentation in configmap for tracing section. Bump chart version

- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/httpproxy.go
- pkg/proxy/engines/objectproxycache.go
- pkg/tracing/registration/registration.go
- pkg/tracing/span/span.go
- pkg/tracing/span/span_test.go
This PR fully eliminates instantiation of tracing package objects unless tracing is enabled in the configuration
> Tracing improvements

- pkg/locks/locks.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/httpproxy.go
- pkg/proxy/engines/key.go
- pkg/proxy/engines/objectproxycache.go
- pkg/proxy/methods/methods.go
- pkg/proxy/origins/influxdb/handler_query.go
- pkg/proxy/origins/influxdb/handler_query_test.go
- pkg/proxy/origins/influxdb/model.go
- pkg/proxy/origins/influxdb/series.go
- pkg/proxy/origins/influxdb/url.go
- pkg/proxy/origins/influxdb/url_test.go
- pkg/proxy/request/request.go
- pkg/proxy/timeconv/timeconv.go
- pkg/timeseries/extent.go
- pkg/timeseries/extent_list.go
this PR addresses a map sort issue in influxdb that can result in a panic at extremely high request volumes, makes associated improvements to named locks, and adds acceleration support for POST requests in InfluxDB
> Influxdb updates

- cmd/trickster/conf/example.conf
- deploy/kube/configmap.yaml
- pkg/proxy/engines/cache.go
- pkg/proxy/engines/cache_test.go
- pkg/proxy/engines/deltaproxycache_test.go
- pkg/proxy/engines/httpproxy_test.go
- pkg/proxy/engines/objectproxycache_test.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/handlers/switch_test.go
- pkg/proxy/listener/listener_test.go
- pkg/proxy/methods/methods_test.go
- pkg/proxy/origins/influxdb/series_test.go
- pkg/proxy/request/request.go
- pkg/proxy/request/request_test.go
- pkg/proxy/tls/tls_test.go
- pkg/util/testing/testing.go
> Test coverage

- .github/workflows/CI_integration_tests_actions.yml
> (#496) added github actions config file for CI test integrations according to the previously used .travis.yml

- cmd/trickster/config.go
- cmd/trickster/listeners.go
- cmd/trickster/signal.go
- pkg/cache/badger/badger.go
- pkg/cache/bbolt/bbolt.go
- pkg/cache/filesystem/filesystem.go
- pkg/cache/index/index.go
- pkg/cache/memory/memory.go
- pkg/cache/redis/redis.go
- pkg/logging/logging.go
- pkg/logging/logging_test.go
- pkg/proxy/engines/access_logs.go
- pkg/proxy/engines/cache.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/document.go
- pkg/proxy/engines/httpproxy.go
- pkg/proxy/engines/objectproxycache.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/handlers/reload.go
- pkg/proxy/listener/listener.go
- pkg/routing/routing.go
- pkg/tracing/registration/registration.go
This updates the previous PR to move the caller back into the log packages but still accurately provides the caller 100% of the time.
Signed-off-by: James Ranson <james_ranson@cable.comcast.com>
> caller update

- README.md
Signed-off-by: Nikola Milojević nikola@mailerlite.com
> add The Remote Company to Trickster user list

- pkg/locks/locks.go
- pkg/locks/locks_test.go
this improves the performance of locks package unit tests when ran in virtualized testing environments
> 1.1 locks tests

- cmd/trickster/main.go
- pkg/proxy/origins/clickhouse/handler_health.go
- pkg/proxy/origins/irondb/handler_health.go
- pkg/proxy/origins/prometheus/handler_health.go
- pkg/proxy/origins/reverseproxycache/handler_health.go
this applies patch #532 to the stable release branch and increments the version in advance of the next release
> 1.1 backport via

- pkg/backends/alb/options/options.go
- pkg/backends/irondb/model/model.go
- pkg/backends/options/options.go
- pkg/observability/tracing/options/options.go
- pkg/observability/tracing/span/span_test.go
- pkg/proxy/paths/options/options.go
- pkg/proxy/request/rewriter/options/options.go
- pkg/proxy/response/merge/merge.go
- pkg/proxy/tls/options/options.go
- pkg/timeseries/dataset/dataset.go
- pkg/timeseries/dataset/point.go
- pkg/timeseries/extent_list.go
- pkg/util/copiers/copiers.go
- pkg/util/copiers/copiers_test.go
- pkg/util/strings/strings.go
- pkg/util/strings/strings_test.go
this patch replaces redundant slice copying patterns with a common copiers package
> 2.0 copiers

- cmd/trickster/main_test.go
- docs/request_rewriters.md
- pkg/backends/alb/first_response_test.go
- pkg/backends/alb/newest_response_test.go
- pkg/backends/alb/response_merge_test.go
- pkg/backends/backend_test.go
- pkg/backends/healthcheck/options/options_test.go
- pkg/backends/options/options_test.go
- pkg/backends/prometheus/model/model.go
- pkg/backends/prometheus/model/timeseries_test.go
- pkg/backends/prometheus/model/vector_test.go
- pkg/backends/rule/rule_test.go
- pkg/encoding/handler/handler_test.go
- pkg/proxy/handlers/redirector_test.go
- pkg/proxy/headers/forwarding_test.go
- pkg/proxy/request/rewriter/rewrite_instructions_test.go
- pkg/proxy/urls/url_test.go
- pkg/util/testing/testing.go
> fix up domain name in examples and tests

- docs/alb.md
- examples/conf/example.full.yaml
- pkg/backends/alb/client.go
- pkg/backends/alb/first_response.go
- pkg/backends/alb/options/options.go
> add custom status codes to fgr alb

- .github/workflows/ci-build-tests.yml
- .spelling
- cmd/trickster/config/loader_test.go
- cmd/trickster/config/reload/options/options.go
- docs/placement.md
- docs/simulated-latency.md
- testdata/ignore_words.txt
this fixes up the issues identified by codespell so the test will pass.
> fix codespell issues

- Makefile
Signed-off-by: jakenichols2719 <jnichols2719@protonmail.com>
> Added serve and related makefile actions to start trickster locally

- pkg/timeseries/dataset/dataset_test.go
- pkg/timeseries/extent_list_test.go
Benchmarks for key functions in timeseries/dataset and timeseries/extent_list
Signed-off-by: jakenichols2719 <jnichols2719@protonmail.com>
> Timeseries Benchmarking

- Dockerfile
- Makefile
Signed-off-by: Tamal Saha <tamal@appscode.com>
> Get `make docker` working again

- .github/workflows/publish-beta-release.yaml
- .github/workflows/publish-release-candidate.yaml
- .github/workflows/publish-release.yml
- .gitignore
- CONTRIBUTING.md
- Dockerfile
- Makefile
- README.md
- docs/developer/tracing.md
> use bin instead of OPATH for build artifacts

- pkg/backends/options/options.go
- pkg/proxy/proxy.go
> Support AWS Sigv4

- .github/workflows/ci-build-tests.yml
- .golangci.yml
- Makefile
- pkg/backends/clickhouse/model/model.go
- pkg/backends/healthcheck/status.go
- pkg/backends/healthcheck/target.go
- pkg/cache/status/lookup_status.go
- pkg/config/config.go
- pkg/observability/logging/logging.go
- pkg/observability/tracing/exporters/otlp/otlp.go
- pkg/proxy/headers/headers.go
- pkg/proxy/ranges/byterange/multipart.go
Adding golangci-lint to the CI & Makefile, and fixing a limited amount of feedback.
I plan to run gofumpt in a separate PR.
> chore: add golangci-lint & minor fixes

- Makefile
- go.mod
- pkg/backends/clickhouse/parsing.go
- pkg/backends/healthcheck/options/options.go
- pkg/backends/influxdb/model/unmarshal.go
- pkg/backends/options/options.go
- pkg/backends/options/options_data_test.go
- pkg/backends/options/options_test.go
- pkg/backends/rule/client.go
- pkg/cache/badger/badger.go
- pkg/cache/badger/badger_test.go
- pkg/encoding/providers/providers.go
- pkg/encoding/reader/reader.go
- pkg/encoding/snappy/snappy.go
- pkg/observability/tracing/exporters/stdout/stdout.go
- pkg/proxy/engines/access_logs.go
- pkg/proxy/engines/access_logs_test.go
- pkg/proxy/engines/document.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/proxy.go
- pkg/proxy/tls/options/options.go
- pkg/timeseries/extent_list.go
- pkg/timeseries/extent_list_test.go
This adds a `make lint` action, and also fixes most of the issues the linter found.
The five remaining issues from the linter will need to be in a separate PR, as they will take more time to investigate and may require more involved refactoring.
> Fix linting issues

- .github/workflows/publish-beta-release.yaml
- .github/workflows/publish-release-candidate.yaml
- .github/workflows/publish-release.yml
- Makefile
Adds a sha256sum.txt file to the release artifact, and refactors the release workflows.
Resolves #569
> feat: [ci/release] add sha256sum to release artifacts and refactor release workflow

- pkg/backends/alb/options/options.go
- pkg/backends/irondb/model/model_df4.go
- pkg/backends/options/options.go
- pkg/cache/negative/negative.go
- pkg/encoding/providers/providers.go
- pkg/timeseries/dataset/dataset.go
* Another pass at using more standard library functions
* Removed an unnecessary mutex from `pkg/timeseries/dataset`
> refactor: increase stdlib usage

- go.mod
- pkg/backends/healthcheck/status.go
- pkg/proxy/handlers/health/health.go
- pkg/proxy/headers/headers.go
- pkg/proxy/ranges/byterange/range.go
- pkg/timeseries/dataset/result.go
- pkg/timeseries/dataset/series.go
- pkg/timeseries/dataset/series_header.go
This replaces all instances where a strings.Builder (`sb`) was doing `sb.WriteString(fmt.Sprintf("%s", myString))` with `fmt.Fprintf(sb, "%s", myString)`.
> more Fprintf fixes

- .github/workflows/ci-build-tests.yml
- .golangci.yml
- Makefile
- pkg/backends/irondb/handler_caql.go
- pkg/backends/irondb/handler_rollup.go
- pkg/backends/prometheus/model/alerts.go
- pkg/backends/prometheus/model/labels.go
- pkg/backends/prometheus/model/series.go
* Upgrade golangci-lint to v2
* Enable new linters (open to toggling these, but these are what led to #774)
* Reduces code duplication
---
Make sure to upgrade golangci-lint, v2 is a breaking update at least as far as the config goes
> chore: remove duplicates & upgrade golangci-lint

- pkg/timeseries/dataset/tags.go
Use more stdlib code in `pkg/dataset/tags.go`
> chore: use generic slice/maps helpers in dataset/tags.go

- Makefile
- pkg/cache/index/index_gen.go
- pkg/config/types/doc.go
- pkg/config/types/envstring.go
- pkg/config/types/envstring_test.go
- pkg/timeseries/dataset/tags_gen.go
- pkg/timeseries/modeler_gen.go
- pkg/util/bytes/bytes.go
- pkg/util/sets/sets.go
- pkg/util/sets/sets_test.go
Update msgpack & generated files.
> chore: update msgpack & associated generated code

- pkg/proxy/engines/progressive_collapse_forwarder.go
Swap a mutex lock for atomics around the progressive collapse forwarders `clientCount` field.
This seems to be the pattern the rest of the code in this file is using already, the sync.Cond is just used for signaling.
> perf: swap lock for atomic usage in engines/pcf

- pkg/proxy/engines/deltaproxycache.go
Another mutex that is safe to remove after swapping append for access by index
> perf: remove locks and ensure consistent results from delta proxy cache fetchExtents helper

- pkg/backends/influxdb/model/unmarshal.go
Removing a channel, and skipping the point sort on error.
> refactor: remove an unnecessary channel from influx unmarshaling

- pkg/proxy/engines/cache.go
Simplify proxy cache code by removing channels.
> perf: remove channels from proxy engine cache

- pkg/cache/cache.go
- pkg/proxy/engines/cache.go
Another micro optimization (from #819 which is probably going to stay open for a while).
As I'm thinking about #807, its helpful to simplify the existing code before rewriting it.
> perf: remove mutex from proxy engine cache

- pkg/proxy/headers/forwarding.go
- pkg/timeseries/dataset/point.go
- pkg/timeseries/extent_list.go
- pkg/util/yamlx/yamlx.go
this is a minor nit PR to range over an integer as supported in recent go versions instead of iterating c-style.
> modernize incrementing ranges

- pkg/cache/index/index.go
Minor refactor to help simplify #819's diff
> refactor: [pkg/cache/index] split reap logic into helper function for upcoming refactor
