trickstercache/trickster

- docs/metrics.md
- metrics.go
Prometheus best practices recommend that base units be used for metrics,
e.g. seconds rather than milliseconds:
https://prometheus.io/docs/practices/naming/#metric-names
/cc @jranson
> Use base units for metrics

- handlers.go
- handlers_test.go
Simplify the request time parsing to only accept values documented in
the Prometheus HTTP API docs:
https://prometheus.io/docs/prometheus/latest/querying/api/
...which also means removing the ability to pass relative times.
Do this to simplify the implementation and align the API more closely to
the values accepted by Prometheus' HTTP API.
Also fixes this error, which I found was occuring whenever a float value
was passed to the API:
time=2018-04-07T11:08:39.715529214Z app=trickster caller=trickster/handlers.go:385 level=error event="request parameter parser error" paramName=start paramValue=1523097519.71 detail="strconv.ParseInt: parsing \"1523097519.71000\": invalid syntax"
> Fix parameter conversion errors and simplify request time parsing

- handlers.go
Prior to this change, we could leak memory if an error occurs while
reading from the response body.
Instead, use defer to ensure that the response body is always closed,
even when error occurs.
> handlers: Defer closing body to avoid leak

- config.go
This PR changes the default cache path  from `/tmp` to `/tmp/trickster` so it aligns with the docs and the sample config file https://github.com/Comcast/trickster/blob/master/conf/example.conf#L45
closes https://github.com/Comcast/trickster/issues/38
> change default cache path to /tmp/trickster

- metrics.go
This PR fixes the incomplete help string for `trickster_requests_total`
closes https://github.com/Comcast/trickster/issues/40
> fix incomplete help string

- handlers.go
The duration was measured in milliseconds, but the metric is for seconds.
closes https://github.com/Comcast/trickster/issues/37
> fix wrong timeunit in trickster_proxy_duration_seconds

- handlers.go
follow up PR to https://github.com/Comcast/trickster/pull/47
The value was represented as an int64 instead of float64, so the value is always rounded down to the nearest whole second.
> use float64 instead of int64 for trickster_proxy_duration_seconds

- handlers.go
* Handle non-200 status codes from Prometheus queries.
* Improve logging of query URLs.
Closes: https://github.com/Comcast/trickster/issues/51
Signed-off-by: Ben Kochie <superq@gmail.com>
> Handle http status on Prometheus queries

- constants.go
- handlers.go
- handlers_test.go
This fixes a number of crashes that currently happen when either the
origin Prometheus cannot be reached or when a user request is faulty.
It also explicitly hard-errors to the user whenever a partial error
happens somewhere in Trickster (due to unreachable origin, faulty JSON
marshaling, or else). There were many cases where an error was logged,
but not handled, causing undefined/crashy behavior. These errors are now
handled and cause the entire request to fail. This seems better than
returning wrong results or crashing.
I also added tests for the obvious crash cases and check whether they
are now returning a user-exposed HTTP error status code instead.
A TODO for the future would be to clean up the metrics handling, since
it currently happens before or after an error return, and errors …
> Enforce strict error handling and early aborts

- Makefile
- handlers_test.go
- main.go
- metrics.go
These changes add _test_ and _test-cover_ targets to the Makefile and fix existing tests so that they do not register duplicate metric handlers or start multiple metric listeners during test cycles.
These changes work toward addressing issue #1. The existing test coverage is 29.6%.
> Test coverage

- config.go
- handlers.go
- handlers_test.go
Prometheus's API requires the "step" parameter to be present in range
queries, so Trickster can do the same instead of providing a default
value.
This also ensures that the step is positive, as otherwise a
divide-by-zero exception can happen further on in
buildRequestContext().
> Require "step" URL parameter in range queries

- handlers.go
The time arg in the params can contain decimal points for more
precision. Before this patch that would cause an error on the time
parse, which was ignored, causing the time sent downstream to be `0`.
This patch (1) properly parses the time as a float64-- then casts to
int64 and (2) checks for errors in the parsing
> Parse the time arg as a float

- handlers.go
Prior to this patch any error unmarshaling from the cache would cause
the request to fail until the item dropped out of cache. This change
simply treats a bad entry as a miss, so it will re-fetch from origin
Fixes #39
> Treat errors unmarshaling from cache as cache miss

- metrics.go
Including "net/http/pprof/" auto-registers profiling endpoints under
/debug/pprof with the default HTTP mux. Since the metrics port HTTP
server uses the default HTTP mux, these get added to the metrics HTTP
server, which seems fitting.
These endpoints are useful in debugging CPU and memory behaviors of
Trickster, and more.
Signed-off-by: Julius Volz <julius.volz@gmail.com>
> Add /debug/pprof endpoints to metrics port

- config.go
- redis.go
We have all of our redis instances setup with authentication which makes using them as a backend impossible.
This change just adds AUTH support to the redis client, based on the presence of password in the configuration file.
> Add option to authenticate with redis servers

- boltdb.go
- conf/example.conf
- config.go
- deploy/helm/trickster/README.md
- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
- deploy/kube/configmap.yaml
- docs/caches.md
* Cleanup docs.
* Use relative file rather than forcing path-based database file.
* Update Helm chart to support boltdb.
Signed-off-by: Ben Kochie <superq@gmail.com>
> Cleanup BoltDB config

- cache.go
Instead of defaulting to cache type memory when misconfigured, panic.
Signed-off-by: Ben Kochie <superq@gmail.com>
Looks like this:
```console
$ trickster -conf invalid.conf
time=2018-10-25T12:19:25.109494354Z app=trickster caller=trickster/main.go:63 level=info event="application startup" version=0.1.1
time=2018-10-25T12:19:25.109628973Z app=trickster caller=trickster/metrics.go:47 level=info event="metrics http endpoint starting" address= port=8082
panic: Invalid cache type: "boom"
goroutine 1 [running]:
main.getCache(0xc000032580, 0xc00000e0d0, 0xc00000e0d8)
/home/ben/go/src/github.com/comcast/trickster/cache.go:49 +0x3c5
main.main()
/home/ben/go/src/github.com/comcast/trickster/main.go:68 +0x32a
```
> Panic when attempting to configure invalid cache

- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/templates/configmap.yaml
If / else chain was broken because of a {{end}} in the way.
helm lint was stating that with the following error:
```
[ERROR] templates/: parse error in "trickster/templates/configmap.yaml": template: trickster/templates/configmap.yaml:53: unexpected {{else}}
```
@LimitlessEarth
> Fixing a problem in helm configmap

- handlers.go
When comparing to another empty struct this should just be checking if
the pointers match, which they don't. In the past this wasn't an issue
since it had no real bearing on the result-- as the body was parsed out
separately. Now that we are actually using this, we need to check
properly. Instead of using a nil I'm checking that the statuscode is
non-zero.
> Fix empty response

- filesystem.go
- handlers.go
Great project! I noticed that the handler references the 200 HTTP status-code in numerous places. It's less error-prone to instead use the status-code constants provided in the `http` package.
Also, use the `%v` formatting verb when formatting an `error` variable rather than invoking `err.Error()`. This was actually a bug: invoking `err.Error()` when  `!writeable(path)` is `true` refers to a nil `err` variable.
> Use built-in HTTP Status Code Constants

- handlers.go
- handlers_test.go
Fix for 9c6aecb53443134537847a5b46b351a5f689b694
The original commit correctly stated that the assumption was that pe2
was before pe, but it actually enforced the exact opposite. This fixes
the enforcement and updates the tests
Fixes #116
> Fix ordering assumption enforcement for mergeMatrix

- redis.go
- redis_test.go
The original redis cache GET call within the redis ReapOnce function has been modified to get all the keys with a single bulk call using the redis client MGET method.
Also, I noticed the reaper goroutine is **not started** within the redis.Connect function. This type of goroutine call for the reaper exists both in the memory.go file and the boltdb.go file. I have added this call to the redis.Connect function.
> Refactor channel reap to use Bulk Get call(Issue #4)

- handlers.go
The max_value_age_secs config in origin doesn't work, Trickster will not drop any old points based on retention policy.
I noticed that in handlers.go:860, in the code use ctx.Matrix.cropToRange(ctx.Time-ctx.Origin.MaxValueAgeSecs, 0), the start=ctx.Time-ctx.Origin.MaxValueAgeSecs use seconds, but the timestamp in metrics from Prometheus use milliseconds, which cause the ts always >= start in cropToRange function, so old data will never be dropped.
> fix max_value_age_secs config doesn't work

- config.go
- handlers.go
In our use of trickster, we meet a problem. In our environment, the query flow is Grafana -> Trickster -> Prometheus_Federation -> Prometheus -> Influxdb.
Prometheus scrape each instance in a interval=10s, Prometheus_Federation collect data from Prometheus in interval=10s. In our use, we find if we query a range of time in grafana, each time after 1min we refresh the dashboard, we find a breakpoint in the dashboard. The query is max_over_time(up[15s]), if we query="up", the datapoint in the join point is not accurate.
In my analysis, I find this is because metrics data from Prometheus to Prometheus_Federation has a latency, Prometheus_Federation collect metrics data from Prometheus in interval=10s, which means Prometheus_Federation not include all metrics data which "timestamp < now()", …
> add no_cache_last_data_secs to let trickster last recent data

- handlers.go
Sorry for code conflict in pull request #120 and #121, this code is based on the latest master code, and the function is same in #120, fix the MaxValueAgeSecs use seconds problem, thanks.
> fix MaxValueAgeSecs filter

- handlers.go
- handlers_test.go
In the testing, I found in the FastForward compare, ctx.RequestExtents.End < ctx.Time-ctx.StepMS, ctx.Time use seconds and others use milliseconds, this merge request fix this bug and the corresponding unit test.
> fix fastforward time ms bug

- deploy/README.md
- deploy/helm/Makefile
- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
- deploy/kube/configmap.yaml
- Helm 2.8.2 -> 2.9.1
- kubectl 1.9.4 -> 1.13.4
- Minikube 0.25.0 -> 0.35.0
- Kube and Helm config maps updated to new format.
- Helm config map is now templated to range over origins and caches in values.
A thought I had while doing this is that we could put the comments of what each thing is in [values.yaml](https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml) in stead of the [configmap](https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-configmap.yaml) like prometheus does in their chart. Thoughts?
> Update helm and kube config maps to follow new format, update versions.

- cmd/trickster/main.go
- go.mod
- internal/proxy/headers.go
- internal/proxy/proxy.go
This ensures that Trickster egresses Prom data down to clients as gzip compressed when the client advertises the proper content-encoding header. Fixes #138
> gzip down to the client

- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/values.yaml
- deploy/kube/configmap.yaml
> Add support for redis cluster configuration in kube artifacts and helm chart

- handlers.go
Hi,
This pr fixes a problem on grafana when you want to have dashboard with parameters.
The request send by grafana for that is something like that: `https://trickster.veepeez.io/api/v1/series?match[]=probe_success&start=1554912065&end=1554913865`
but grafana can't display the result.
in the browser console I have the following message:
@trickster-reviewers
> Add cors support for queries like series

- docs/promsim.md
- pkg/promsim/promsim.go
- pkg/promsim/promsim_test.go
- Filled in the usageCurveVal function with a sinusoidal wave function peaking at 8pm local
- This could probably be changed to something even more realistic, but this is a good start. 
- Multiple series are supported by scaling the max value randomly past the first.
> Promsim curve

- pkg/promsim/http_server.go
on requests to /query, the time parameter is optional and should default time to Now() instead of returning an error if missing
> PromSim parameter fix

- internal/proxy/origins/prometheus/routes.go
- internal/util/metrics/metrics.go
- internal/util/middleware/metrics.go
- internal/util/middleware/observer.go
This PR provides a set of metrics for return codes and durations from the front end perspective of the cache.
These metrics are:
1. trickster_frontend_requests_total *counter*
2. trickster_frontend_requests_duration_seconds *histogram*
3. trickster_frontend_written_bytes_total *counter*
All metrics have the following labels:
1. http_status which follows the haproxy style of status code grouping them by hundreds (2xx, 3xx, etc)
2. method - GET/POST
3. origin_name
4. origin_type
5. path which only provides the general handler, for example: proxy, query, query_range, status, etc.
Still pending implement the same for other backends besides prometheus.
> Observe frontend requests

- internal/cache/badger/badger.go
- internal/cache/bbolt/bbolt.go
- internal/cache/cache.go
- internal/cache/filesystem/filesystem.go
- internal/cache/memory/memory.go
- internal/cache/redis/redis.go
While checking for bolt specific metrics I noticed that trickster is not accounting for how many cache keys are being deleted, and I think it's an interesting metric to be aware of.
> Add deletes counter metrics

- deploy/helm/trickster/templates/deployment.yaml
I isolated these changes as they ship with some behavior changes from what exists today:
- Adds the magic shebang to trigger a rollout on configmap update. Uses
the helm sha256 sum crc as an annotation.
- A potential controversial update to the healthcheck. I noticed in
multi-origin deployments that trickster would fail to pass its
readiness check. This is due to how trickster itself passes the /health check
to the "default origin" in all cases. if the default is down, or
otherwise misconfigured (or missing!) the healthcheck will fail and
trickster will never enter a ready state. This caused a lot of confusion and some healthy debugging.
I discovered the second point quite by accident as rolling from a single origin to multi-origin broke in very interesting ways with the state of the …
> Update the Healthcheck and auto-roll on configmap update

- internal/proxy/engines/deltaproxycache.go
- internal/proxy/engines/httpproxy.go
- internal/proxy/errors/errors.go
- internal/proxy/errors/errors_test.go
- internal/proxy/origins/irondb/handler_caql.go
- internal/proxy/origins/irondb/handler_fetch.go
- internal/proxy/origins/irondb/handler_fetch_test.go
- internal/proxy/origins/irondb/handler_histogram.go
- internal/proxy/origins/irondb/handler_rollup.go
- internal/proxy/origins/irondb/irondb.go
- internal/proxy/origins/irondb/key.go
- internal/proxy/origins/irondb/key_test.go
- internal/proxy/origins/irondb/model.go
- internal/proxy/origins/irondb/model_df4.go
- internal/proxy/origins/irondb/model_df4_test.go
- internal/proxy/origins/irondb/routes.go
- internal/proxy/origins/irondb/url.go
- internal/proxy/origins/irondb/url_test.go
- Adds origin handler support for the IRONdb /fetch API.
- That API uses POST requests, so handling of client request body support is added.
- Fixes issues with cache key generation preventing IRONdb CAQL requests from using the delta cache properly.
- Fixes an issue with time request query parsing for IRONdb histogram requests.
- Fixes an issue preventing proper delta cache utilization for IRONdb rollup requests involving requests for time ranges with the same start and end times.
> Add IRONdb origin fetch API support

- cmd/trickster/conf/example.conf
- cmd/trickster/main.go
- go.mod
- internal/config/config.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
- internal/util/metrics/metrics.go
This commit adds the ability to configure a limit of connections handled by the front end proxy. It is implemented using go's [x/net/netutil/LimitedListener][1]
Additionally, using the same technique, I am wrapping the listener to provide multiple metrics of front end connections:
1. Active connections (Gauge)
1. Requested (Counter)
1. Accepted (Counter)
1. Failed (Counter)
1. Closed (Counter)
This can be useful to determine how many connections are necessary at any point, and to identify spikes of any kind from the client side.
The way it behaves is that by default the limit is 0, which means unlimited, and all we get is metrics.
In the case of setting a limit, when a client requests a new connection and we run out of them, the request locks until there's one available (or the client …
> Add proxy connections limit

- Makefile
- cmd/trickster/main.go
I have added the build time using `date -u %FT%T%z` which gives sample timestamp 2019-10-11T07:46:1707:46:17+0000 which seems to be the standard according to [here](https://stackoverflow.com/questions/11354518/application-auto-build-versioning) and [here](https://github.com/commissure/go-git-build-vars/blob/master/Makefile). I made 2 global variables in `cmd/trickster/main.go` applicationBuildTime and applicationGitCommitID which are set during build time from the Makefile using `-ldflags` option.
@jranson please let me know if any changes are required/recommended.
> added build time and commit ID to the binary

- deploy/helm/trickster/templates/configmap.yaml
If  redis is used as a cache type (`{{- if eq .type "redis" }}`), the template skips all the settings, independently of if you use standard, cluster or sentinel, as the following else if statement follows the mentioned one: `{{- else if eq .redis.clientType "standard" }}`. This pull request suggests changing the following block:
```
{{- if eq .type "redis" }}
....
{{- else if eq .redis.clientType "standard" }}
...
{{- else if or (eq .clientType "cluster") (eq .clientType "sentinel") }}
...
{{- if eq .clientType "sentinel" }} 
...
{{- end }}
{{- end }}
```
To:
```
{{- if eq .type "redis" }}
....
{{- if eq .redis.clientType "standard" }}
...
{{- else if or (eq .clientType "cluster") (eq .clientType "sentinel") }}
...
{{- if eq .clientType "sentinel" }} 
...
{{- end }}
{{- end }}
{{- end }} …
```
> Fix if condition in configmap template when using redis as cache type

- deploy/helm/trickster/templates/service.yaml
- deploy/helm/trickster/values.yaml
Fixes a parsing error when enabling prometheus scraping annotations. The values need to be quoted so that helm is able to parse them correctly.
Also, the prometheusScrape parameter was not part of the values.yaml.
> 1.0 fix prometheus annotations

- cmd/trickster/main.go
The `:=` after the if statement on line 99 was scoping err inside of that if. The error would never be logged if it was not nil.
> Expose scoped error for tls server

- cmd/trickster/conf/example.conf
- internal/config/config.go
- internal/proxy/engines/objectproxycache.go
- testdata/test.full.conf
- testdata/test.redis-cluster.conf
- testdata/test.redis-sentinel.conf
- testdata/test.redis-standard.conf
This allows a max cache object size on a per origin basis.
This makes the answer to "should we proxy the request or cache it?" more knowable at the time of the request. 
If we are just proxying a request and want to collapse it(see #284) we can check if the resulting memory usage would be too much - such that we can only proxy.
> Move max object size to origin config

- internal/routing/registration/registration.go
route registration will always use reverse alphabetical, meaning longest match always wins.  this works because all trickster paths are expected to be absolute or prefixed, with no parameter variables that gorilla might support.
> ensure reliable path ordering at registration

- Makefile
Current error encountered:
> mkdir -p ./OPATH/SOURCES
> cp -p trickster ./OPATH/SOURCES/
> cp: cannot stat ‘trickster’: No such file or directory
> make: *** [rpm] Error 1
In the `next` branch, the trickster binary is placed in ./OPATH.  The Makefile needs to be updated to use this new path when building the RPM
> trickster binary not in `cp` path for `make rpm`

- Makefile
I try to deploy trickster with Ansible, but Ansible doesn't support `.gz` release file. [From Ansible  unarchive docs](https://docs.ansible.com/ansible/latest/modules/unarchive_module.html):
- Can handle .zip files using unzip as well as .tar, .tar.gz, .tar.bz2 and .tar.xz files using gtar.
- Does not handle .gz files, .bz2 files or .xz files that do not contain a .tar archive.
So I recommend trickster releases with `tar.gz` format, please consider this request. Example Ansible code
> Release with tar.gz format instead of only gz format (support Ansible unarchive module)

- internal/proxy/engines/progressive_collapse_forwarder.go
The return on line 121 would cause the waitgroup to never finish. Use defer instead.
> Patch waitgroup leak on multiple return

- internal/proxy/engines/progressive_collapse_forwarder.go
- internal/proxy/engines/progressive_collapse_forwarder_test.go
- Minor changes in the PCF code itself to better use sync.Cond as described [in the docs](https://golang.org/pkg/sync/#Cond.Wait).
- Added tests to wait server and wait all.
- Removed manual set N for benchmarks.
> Get test coverage to 100 on pcf

- internal/config/path.go
- internal/proxy/engines/key.go
- internal/proxy/engines/key_test.go
- internal/proxy/origins/irondb/handler_fetch.go
- internal/proxy/origins/irondb/handler_fetch_test.go
- internal/proxy/origins/irondb/handler_histogram.go
- internal/proxy/origins/irondb/handler_histogram_test.go
- internal/proxy/origins/irondb/handler_text.go
- internal/proxy/origins/irondb/handler_text_test.go
this patch addresses an issue where key hashers that read request body content are not able to reset set the request body to byte 0 for additional processors to read it as well (e.g, in the event of a cache miss when the request body needs to be forwarded to an origin server).
> fix ineffectual assignment in irondb custom key hasher

- deploy/helm/trickster/Chart.yaml
- deploy/helm/trickster/templates/configmap.yaml
- deploy/helm/trickster/templates/deployment.yaml
- deploy/helm/trickster/templates/ingress.yaml
- deploy/helm/trickster/templates/pvc.yaml
- deploy/helm/trickster/values.yaml
Fixes:
1. label selectors not matching labels
2. missing config mount path
3. unquoted `1.0` image tag truncates to `1`, which is not the same image tag.
4. change mounting path pattern now that we have multiple configs
5. fix ingress controller templating
The first issue relates to [label selector updates](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates)
Not sure how the second issue came about. No matter what was changed my config values were not reflected -> missing volume mount. The helm templated trickster config was never being exposed in the pod.
Last issue is just a simple fix due to how helm does numbers.
This is probably the beefiest section of the rework.
The new scheme supports multiple many to one and many to many relationships …
> Helm Updates

- internal/util/middleware/config_context.go
```
2020/02/13 14:41:11 http: panic serving 127.0.0.1:56594: runtime error: invalid memory address or nil pointer dereference
goroutine 462008 [running]:
net/http.(*conn).serve.func1(0xc0000b1540)
/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xacdb80, 0x1154c30)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/Comcast/trickster/internal/util/middleware.WithResourcesContext.func1(0xca2460, 0xc000191180, 0xc0003eef00)
/go/src/github.com/Comcast/trickster/internal/util/middleware/config_context.go:29 +0x83
net/http.HandlerFunc.ServeHTTP(0xc000157130, 0xca2460, 0xc000191180, 0xc0003eef00)
/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00017e000, 0xca2460, 0xc000191180, 0xc0003eeb00) …
```
> Fix health probe runtime error

- deploy/helm/trickster/templates/service.yaml
At the moment, an annotation is needed in order to enable prometheus annotatios, as the section ```annotations``` is inside the ```if``` condition:
```
{{- if .Values.service.annotations }}
annotations:
prometheus.io/scrape: {{ .Values.prometheusScrape | quote }}
prometheus.io/port: {{ .Values.service.metricsPort | quote }}
prometheus.io/path: /metrics
{{- end }}
```
The proposed change will allow enabling any annotations without enabling prometheus annotations and vice versa.
> Allow to enable prometheus metrics without any annotations and viceversa

- deploy/helm/trickster/templates/service.yaml
Istio supports proxying all TCP traffic by default, but in order to provide additional capabilities, such as routing and rich metrics, the protocol must be determined.
https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/
> Helm service ports

- cmd/trickster/main.go
- internal/cache/badger/badger.go
- internal/cache/badger/badger_test.go
- internal/cache/bbolt/bbolt.go
- internal/cache/bbolt/bbolt_test.go
- internal/cache/cache.go
- internal/cache/filesystem/filesystem.go
- internal/cache/filesystem/filesystem_test.go
- internal/cache/index/index.go
- internal/cache/index/index_test.go
- internal/cache/memory/memory.go
- internal/cache/memory/memory_test.go
- internal/cache/redis/redis.go
- internal/cache/redis/redis_test.go
- internal/proxy/engines/cache_test.go
- internal/proxy/engines/client_test.go
- internal/proxy/engines/deltaproxycache.go
- internal/proxy/engines/proxy_request.go
- pkg/locks/locks.go
- pkg/locks/locks_test.go
This addresses 2 separate issues:
- Mitigate mutex deadlocks leading to too many open files #391, #397 
- Fix "context canceled" and false flag "502 Bad Gateway" errors when downstream clients cancel a request.
> V1.0.3 bugfix

- go.mod
- go.sum
- pkg/cache/badger/badger.go
- pkg/cache/badger/badger_test.go
- pkg/cache/bbolt/bbolt.go
- pkg/cache/bbolt/bbolt_test.go
- pkg/cache/cache.go
- pkg/cache/filesystem/filesystem.go
- pkg/cache/filesystem/filesystem_test.go
- pkg/cache/memory/memory.go
- pkg/cache/memory/memory_test.go
- pkg/cache/redis/redis.go
- pkg/cache/redis/redis_test.go
- pkg/cache/registration/registration.go
- pkg/locks/locks.go
- pkg/locks/locks_test.go
- pkg/proxy/engines/cache.go
- pkg/proxy/engines/cache_test.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/deltaproxycache_test.go
- pkg/proxy/engines/document.go
- pkg/proxy/engines/objectproxycache.go
- pkg/proxy/engines/objectproxycache_test.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/engines/proxy_request_test.go
- vendor/modules.txt
This PR will updates the Named Locks packages to eliminate package-level access and anonymous locking/unlocking, while adding an exportable Locker, RWMutex support, and an Upgrade function to morph a read lock into a write lock, while maintaining continuity. RWMutex implementation is added to the Delta Proxy Cache and Object Proxy Cache.
> Use RWMutex

- pkg/proxy/origins/prometheus/prometheus.go
- pkg/timeseries/timeseries.go
This patch will check if the provided prometheus query contains the string `trickster-fast-forward:off` and, if so, will disable the fast forward feature for the query. If Fast Forward is disabled at the origin level, including this string in the query will be ineffectual. Likewise, this patch provides no ability to enable fast forward for queries when it is disabled at the origin level.
Safe usage is to add a comment to the end of a PromQL query as follows:
```
go_goroutines{job="trickster"} # trickster-fast-forward:off
```
> add per-query fast-forward-disable ability (prom)

- pkg/config/defaults/defaults_windows.go
this patch updates the default paths to reside under `.` for Windows compilations.
> update windows default paths

- docs/paths.md
Hopefully micro-changes like this (especially just to documentation) aren't unwelcome noise. I and some others on my team have been hitting the documentation hard; sometimes broken links are a bit jarring to hit when you're in deep-thonk mode. 😄
> Fix broken link and misspleling

- pkg/cache/index/index.go
- pkg/proxy/origins/clickhouse/series.go
- pkg/proxy/origins/clickhouse/series_test.go
- pkg/proxy/origins/influxdb/series.go
- pkg/proxy/origins/influxdb/series_test.go
- pkg/proxy/origins/irondb/model.go
- pkg/proxy/origins/irondb/model_df4.go
- pkg/proxy/origins/irondb/model_df4_test.go
- pkg/proxy/origins/irondb/model_test.go
- pkg/proxy/origins/prometheus/matrix.go
- pkg/proxy/origins/prometheus/matrix_test.go
- pkg/timeseries/extent_list.go
this pr improves accuracy of cache size calculation for memory and bbolt caches.
> Cache size measurements

- pkg/proxy/engines/cache.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/document.go
- pkg/proxy/engines/objectproxycache.go
this PR addresses potential map contention panics during the shared use of headers of a cached object, when simultaneous cache hits are handled for that object.
> additional header access thread safety

- pkg/cache/bbolt/bbolt.go
- pkg/cache/filesystem/filesystem.go
- pkg/cache/memory/memory.go
- pkg/proxy/engines/deltaproxycache.go
this prevents a race condition where a cache mutex could be unlocked before the object is fully written, and eliminates a package globals.
> cache optimizations

- pkg/proxy/engines/cache.go
- pkg/proxy/engines/deltaproxycache.go
this PR will properly log errors when a cache object fails to marshal or unmarshal
> better err logging when marshaling fails

- pkg/proxy/origins/clickhouse/clickhouse.go
- pkg/proxy/origins/client.go
- pkg/proxy/origins/influxdb/influxdb.go
- pkg/proxy/origins/irondb/irondb.go
- pkg/proxy/origins/mock_client_test.go
- pkg/proxy/origins/prometheus/prometheus.go
- pkg/proxy/origins/reverseproxycache/rpc.go
- pkg/proxy/origins/timeseries_client.go
This is just some minor tidying that helps ensure the origin clients are implementing the proxy client interface. I assumed/hoped `Cache` was acceptable to add to the interface, but am fine with the possibility it was intentionally left out.
> Add Cache to proxy Client interface. Enforce origins implement Client

- pkg/proxy/engines/client_test.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/key.go
- pkg/proxy/engines/key_test.go
- pkg/proxy/origins/clickhouse/clickhouse.go
- pkg/proxy/origins/clickhouse/stubs.go
- pkg/proxy/origins/clickhouse/stubs_test.go
- pkg/proxy/origins/influxdb/influxdb.go
- pkg/proxy/origins/influxdb/stubs.go
- pkg/proxy/origins/influxdb/stubs_test.go
- pkg/proxy/origins/influxdb/url.go
- pkg/proxy/origins/irondb/handler_caql.go
- pkg/proxy/origins/irondb/handler_caql_test.go
- pkg/proxy/origins/irondb/handler_histogram.go
- pkg/proxy/origins/irondb/handler_histogram_test.go
- pkg/proxy/origins/irondb/handler_rollup.go
- pkg/proxy/origins/irondb/handler_rollup_test.go
- pkg/proxy/origins/irondb/url.go
- pkg/proxy/origins/irondb/url_test.go
- pkg/proxy/origins/prometheus/url.go
- pkg/proxy/origins/prometheus/url_test.go
- pkg/proxy/origins/timeseries_client.go
- pkg/proxy/request/request.go
this PR ensures that POST requests are fully supported with Fast Forward. It also administratively sets` FastForwardDisabled` to `true` on InfluxDB and ClickHouse, since their accelerators do not currently implement the feature.
The key change was to replace `FastForwardURL()` in the Timeseries Client interface to `FastForwardRequest()` which handles the entire FF Request creation instead of just url manipulation, allowing access to the request body for POSTs.
> Ffw post fixes

- pkg/proxy/engines/deltaproxycache.go
this patch ensures that Trickster will not panic when an upstream Fast Forward Request fails and returns a nil response, and ensures that if the cache object fails marshaling for some reason, the cache record is not deadlocked. #452
> fix nil resp panic & deadlock

- pkg/proxy/origins/influxdb/series.go
When multiple statement in query series metric are lost. Refers to issue #460
> Fix losing series when multiple statements in query.

- .travis.yml
Added arm64 jobs (with python and Go: 1.14.x) in .travis.yml
Signed-off-by: odidev odidev@puresoftware.com
> Added arm64 support to travis-ci

- docs/configuring.md
This brings the documentation into alignment with the actual environment variable name that's required. Also one tiny spelling fix. :smile:
Issue this is in reference to: https://github.com/tricksterproxy/trickster/issues/490
> env URL name fix

- deploy/kube/configmap.yaml
- deploy/trickster-demo/docker-compose-data/trickster-config/trickster.conf
- docs/metrics.md
- docs/multi-origin.md
- docs/negative-caching.md
- docs/paths.md
- docs/range_request.md
- docs/rule.md
- pkg/util/metrics/metrics.go
Updated "origin_type" and "cache_type" references in documentation referred in these comments (https://github.com/tricksterproxy/trickster/issues/495#issuecomment-702250964 , https://github.com/tricksterproxy/trickster/issues/495#issuecomment-702253173 ) to "provider", resolving https://github.com/tricksterproxy/trickster/issues/495.
Issue was assigned but on seeing that, last update was 5 days ago, and by non-assignee whose PR was merged, encouraged me to resolve.
Please add `hacktoberfest-accepted` label, so that contribution will count towards my hacktoberfest participation.
Thanks!
> Updated references from old names to new ones

- cmd/trickster/config.go
- cmd/trickster/listeners.go
- cmd/trickster/signal.go
- pkg/cache/badger/badger.go
- pkg/cache/bbolt/bbolt.go
- pkg/cache/filesystem/filesystem.go
- pkg/cache/index/index.go
- pkg/cache/memory/memory.go
- pkg/cache/redis/redis.go
- pkg/logging/logging.go
- pkg/logging/logging_test.go
- pkg/proxy/engines/access_logs.go
- pkg/proxy/engines/cache.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/document.go
- pkg/proxy/engines/httpproxy.go
- pkg/proxy/engines/objectproxycache.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/handlers/reload.go
- pkg/proxy/listener/listener.go
- pkg/routing/routing.go
- pkg/tracing/registration/registration.go
this fixes an issue where the `caller` field in a 2.0 log was never accurate; with this change, it is 100% of the time. the meat of this change is in logging.go (requiring the caller to pass in it's stack.Call for Debug, Info, Warn, etc. All other files changed are solely for conforming to the updated logging function prototypes.
> 2.0 fix log caller

- pkg/backends/providers/providers.go
- pkg/backends/providers/providers_test.go
- pkg/backends/reverseproxy/handler_health.go
- pkg/backends/reverseproxy/handler_health_test.go
- pkg/backends/reverseproxy/handler_proxy.go
- pkg/backends/reverseproxy/handler_proxy_test.go
- pkg/backends/reverseproxy/routes.go
- pkg/backends/reverseproxy/routes_test.go
- pkg/backends/reverseproxy/rp.go
- pkg/backends/reverseproxy/rp_test.go
- pkg/routing/routing.go
- pkg/util/metrics/metrics.go
This contribution adds a basic reverse proxy to Trickster by using provider type `rp`, `proxy`, or `reverseproxy`. It has always been possible to configure the Reverse Proxy Cache backend to use the proxy instead of the proxy cache; but this new provider type is more direct and does not require any under-the-hood customization knowledge in order to accomplish this basic feature.
> 2.0 basic proxy

- pkg/locks/locks.go
- pkg/locks/locks_test.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/objectproxycache.go
- pkg/proxy/engines/proxy_request.go
this PR improves Named Locks performance and reliability throughout the application.
> named lock performance improvements

- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/httpproxy_test.go
- pkg/proxy/origins/influxdb/tokenization.go
- pkg/proxy/origins/influxdb/url.go
- pkg/proxy/origins/influxdb/url_test.go
As explained in #466, when the date range specified is partially catched, the `missRanges` are not calculated properly, generating queries that return gaps in the series.
> Using closed intervals to avoid gaps in partially cached timeseries

- pkg/proxy/engines/proxy_request.go
As comented on #522, access log debug lines are misleading. Trickster is logging as upstream request the actual input path (without the origin prefix path) and query string but with the upstream host instead of Trickster's. This can be observed easily for partially catched time series: Trickster queries the upstream multiple times with the missing date intervals but the logged URL is always the same.
A repro case:
Query Trickster for `/influx1/query?db=inspectit&epoch=ms&q=SELECT+mean%28%22value%22%29+FROM+%22system_load_average_1m%22+WHERE+%28%22host%22+%3D~+%2F%5E44a9e042a4ca%24%2F%29+AND+time+%3E%3D+1611480030000ms+and+time+%3C%3D+1611481500000ms+GROUP+BY+time%2830s%29+fill%28linear%29"`. This should log several missing date interval fetched from upstream, but instead we got the same …
> Log upstream request URL instead of the original URL object

- pkg/proxy/engines/proxy_request.go
Backport to `1.1.x` branch from #524
> Log upstream request URL instead of the original URL object (backport to 1.1.x)

- pkg/backends/prometheus/handler_query.go
- pkg/backends/prometheus/options/defaults.go
- pkg/backends/prometheus/prometheus.go
- pkg/backends/prometheus/prometheus_test.go
this allows a user-configurable rounding value for instantaneous prometheus queries, instead of hardcoding to 15 seconds. (Default is still 15)
> configurable rounding value for instant queries

- docs/rule.md
- pkg/backends/rule/operations.go
- pkg/backends/rule/operations_test.go
- pkg/backends/rule/parse.go
this patch adds an `rmatch` operation capability to the Rules backend type. Users can provide regex's in the configuration file, which are compiled at startup, to match against HTTP Request parts as a rule compilation.
> add regex matching operation to rules

- docs/request_rewriters.md
- pkg/proxy/context/hops.go
- pkg/proxy/context/resources.go
- pkg/proxy/request/rewriter/options/option_test.go
- pkg/proxy/request/rewriter/options/options.go
- pkg/proxy/request/rewriter/rewrite_instructions.go
- pkg/proxy/request/rewriter/rewrite_instructions_test.go
- pkg/proxy/request/rewriter/rewriter.go
- pkg/proxy/request/rewriter/rewriter_test.go
this patch adds a chain rewriter type, permitting a configuration to call request rewriters from other request rewriters, to help reduce the number of duplicated rewriter rules
> add chain rewriter type

- pkg/backends/irondb/model/model.go
- pkg/backends/irondb/model/model_df4.go
- pkg/backends/options/defaults.go
- pkg/backends/options/options.go
- pkg/backends/options/options_data_test.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/deltaproxycache_test.go
- pkg/timeseries/dataset/dataset.go
- pkg/timeseries/extent.go
- pkg/timeseries/extent_list.go
- pkg/timeseries/extent_list_test.go
- pkg/timeseries/extent_test.go
- pkg/timeseries/modeler_test.go
- pkg/timeseries/request_options_test.go
- pkg/timeseries/timerangequery.go
- pkg/timeseries/timerangequery_test.go
- pkg/timeseries/timeseries.go
This patch changes the backfill tolerance pattern, which is used to prevent preliminary real-time data from being cached until it is old enough to be considered final, from an eager load to a lazy load pattern.
The previous implementation would simply not cache data new enough to fall in the backfill tolerance window. As a result, every single real-time request to Trickster for the given Backend would result in a partial cache hit at best, since some data would always be excluded from the cache and need to be fetched. There was no possibility of a Cache Hit for time series requests on backends with a backfill tolerance set.
The new approach improves the methodology by caching the the preliminary data and serving to subsequent requests, so long as the lookup is otherwise a cache hit. once …
> 2.0 backfill tolerance update

- cmd/trickster/config.go
- pkg/routing/routing.go
- pkg/routing/routing_test.go
a previous patch relocated the /trickster/health handler to the metrics port listener instead of the proxy port listener. backend-specific health paths (eg.. /trickster/health/backendName) were still routing over the proxy port. This patch moves those to the metrics port as well.
> route /trickster/health/<backen> via metrics port

- CONTRIBUTING.md
- GOVERNANCE.md
- MAINTAINERS.md
- SECURITY.MD
- docs/roadmap.md
This PR refreshes the Trickster Project's Governance documents to align with CNCF project principles, and relocates security vulnerability instructions from CONTRIBUTING.md to a separate SECURITY.md document, to address #566 
Additionally, this documents me as the Project Lead and establishes a renewable 1yr term, per the Governance Docs, beginning on 3/22/21 (when Trickster was transferred to CNCF).
> refresh governance docs

- README.md
pkg/encoding/brotli (among others) requires 1.16
```
github.com/trickstercache/trickster/pkg/backends/irondb/model
pkg/backends/irondb/model/model.go:395:10: undefined: io.ReadAll
note: module requires Go 1.16
github.com/trickstercache/trickster/pkg/errors
github.com/trickstercache/trickster/pkg/util/timeconv
github.com/trickstercache/trickster/pkg/util/base64
github.com/trickstercache/trickster/pkg/util/sha1
internal/profile
github.com/trickstercache/trickster/pkg/encoding/zstd
github.com/trickstercache/trickster/pkg/encoding/brotli
runtime/pprof
pkg/encoding/brotli/brotli.go:31:9: undefined: io.ReadAll
note: module requires Go 1.16
os/signal
net/http/pprof
github.com/influxdata/influxql/internal
github.com/influxdata/influxql
make: *** [Makefile:58: build] Error 2
```
> bump required golang version

- examples/packages/cache/bbolt/README.md
- examples/packages/cache/bbolt/main.go
- examples/packages/cache/memory/README.md
- examples/packages/cache/memory/main.go
- pkg/cache/bbolt/bbolt.go
- pkg/cache/index/options/options.go
- pkg/cache/memory/memory.go
This PR makes it much easier for other go projects to import and use the Trickster memory and bbolt caches, and provides example apps for each.
> Cache examples

- docs/simulated-latency.md
- examples/conf/example.full.yaml
- pkg/backends/options/options.go
- pkg/util/middleware/config_context.go
this patch will allow the user to provide latency_min_ms and/or latency_max_ms values to introduce simulated latency into inbound requests.
> add simulated latency functionality

- Makefile
- cmd/trickster/config.go
- cmd/trickster/main.go
- cmd/trickster/usage.go
- cmd/trickster/usage_test.go
This patch updates the `initLogger()` and `PrintVersion()` functions to use the correct flags for reporting a build's target os, arch, and go version at runtime from the compiled binary.
> build and report correct target os/arch

- pkg/backends/healthcheck/options/options.go
- pkg/backends/healthcheck/options/options_test.go
- pkg/backends/options/options_data_test.go
This corrects a few places where the legacy 1.x config value for health checks of `upstream_path` was not updated to just `path` when migrating code over to 2.x
fixes #617
> use path instead of upstream_path

- cmd/trickster/config/env.go
this patch addresses incorrect conversion between integer types when loading port configs
> set int upper bound

- pkg/backends/influxdb/handler_query.go
Adds the capability from IronDB to cache SELECT requests in the short term to InfluxDB.
> Non ts cache

- pkg/observability/logging/logging.go
- pkg/proxy/listener/listener.go
this patch ensures that fatal startup errors are reliably logged before the application exits
fixes #627
> reliably print fatal startup errors

- pkg/timeseries/dataset/dataset.go
- pkg/timeseries/dataset/dataset_test.go
- pkg/timeseries/dataset/series_list.go
- pkg/timeseries/dataset/tags.go
this eliminates a potential nil pointer panic when a series may be nil during tag injection. fixes #633 
> add nil pointer check on tags injection

- README.md
- pkg/routing/routing.go
When the default backend routes are registered, currently it is as per unordered map. This means that the routes can have "" or "\api\v1" before "api\v1\query_range". When the router matches the regex expression (Refs: https://gecgithub01.walmart.com/Telemetry/trickster-v2/blob/main/pkg/router/route.go#L40 https://gecgithub01.walmart.com/Telemetry/trickster-v2/blob/main/pkg/router/regexp.go#L323) with the routes map, if partial routes appears first that will be considered as a match, which causes request to be "Proxy-Only".
Thus, with sorting we will ensure that routes will be a sorted array in the descending order of path lengths, meaning: "\api\v1\query_range" would appear before "api\v1" and "" so that we have appropriate match. …
> Sort the paths in routes to ensure matcher picks nearest regex to request uri

- Dockerfile
- pkg/backends/influxdb/flux/flux.go
- pkg/backends/influxdb/flux/parser.go
- pkg/backends/influxdb/flux/parser_test.go
- pkg/backends/influxdb/handler_query.go
- pkg/backends/influxdb/handler_query_test.go
- pkg/backends/influxdb/model/unmarshal.go
- pkg/backends/influxdb/model/unmarshal_test.go
- pkg/backends/influxdb/routes.go
- pkg/backends/influxdb/routes_test.go
- pkg/backends/influxdb/url.go
- pkg/backends/influxdb/url_test.go
- pkg/backends/prometheus/url_test.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/key.go
- pkg/proxy/headers/headers.go
- pkg/proxy/params/params.go
- pkg/proxy/params/params_test.go
Fixing some errors that I left in the Flux implementation. Queries should now properly parse from the request body for POST requests (idiomatic for flux), and should use the OPC if there's no timestep, which is now parsed out of the first `window()` or `aggregateWindow()` found in the query, since using different timesteps for data in the DeltaProxyCache is probably bad.
Running some tests with InfluxDB 2.0 locally and will undraft once that's done and confirmed OK.
> Flux fixes

- pkg/proxy/engines/httpproxy.go
Now "request_headers" sets only if "request_params" is not empty. But it seems to me that these parameters should be controlled separately.
> separate UpdateHeaders from UpdateParams

- pkg/backends/clickhouse/handler_query.go
- pkg/proxy/engines/objectproxycache_chunk_test.go
- pkg/proxy/engines/objectproxycache_test.go
Issue 696 was describing an issue with multi-line queries in ClickHouse, where if a query started with SELECT immediately followed by a newline, it would not get cached. The parser previously only looked for SELECT or SELECT (including spaces), so this adds SELECT\n to the list. Also removed a make call that was unused.
> Clickhouse fix

- .github/workflows/publish-beta-release.yaml
- .github/workflows/publish-release-candidate.yaml
- .github/workflows/publish-release.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- pkg/backends/clickhouse/parsing_test.go
- pkg/parsing/lex/lex.go
- pkg/parsing/lex/run_state.go
- pkg/parsing/lex/run_state_test.go
- pkg/parsing/lex/sql/sql.go
- pkg/parsing/lex/sql/sql_test.go
- pkg/parsing/run_state.go
- pkg/parsing/run_state_test.go
- pkg/parsing/sql/select.go
- pkg/parsing/sql/select_test.go
- pkg/parsing/sql/sql.go
- pkg/parsing/sql/sql_test.go
- pkg/parsing/token/token.go
- pkg/parsing/token/token_test.go
- pkg/timeseries/sqlparser/sqlparser_test.go
This patch improves the SQL Lexer/Parser performance by refactoring from the previous scheme of concurrent lexing/parsing via channels to a lex-then-parse scheme that is more performant due to a 100% removal of channels in the request path.
> SQL Parser Performance

- pkg/proxy/engines/cache_chunk_test.go
- pkg/proxy/engines/cache_test.go
- pkg/proxy/engines/document.go
- pkg/proxy/engines/proxy_request_test.go
- pkg/proxy/headers/headers.go
- pkg/proxy/params/params.go
- pkg/proxy/ranges/byterange/multipart.go
- pkg/proxy/tls/options/options.go
this removes duplicative nil checks where the length of the slice or map is also being checked
because unit tests on main currently fail from recent package updates, this PR is expected to fail unit tests too. will address failing tests in a separate PR.
> remove unneeded nil checks

- pkg/backends/clickhouse/clickhouse.go
- pkg/backends/clickhouse/model/model.go
- pkg/backends/clickhouse/model/model_test.go
- pkg/backends/clickhouse/url.go
- pkg/backends/influxdb/model/marshal.go
- pkg/backends/influxdb/model/marshal_test.go
- pkg/backends/influxdb/model/model.go
- pkg/backends/influxdb/model/unmarshal.go
- pkg/observability/tracing/exporters/otlp/otlp.go
- pkg/proxy/engines/deltaproxycache_test.go
- pkg/proxy/engines/key.go
- pkg/proxy/response/response.go
- pkg/timeseries/dataset/dataset.go
- pkg/timeseries/dataset/dataset_test.go
- pkg/timeseries/request_options.go
This PR makes several updates to correct the remaining linter issues:
* changes `timerseries.Marshaler` function type to return a `[]byte` instead of requiring an `io.Writer`
* this bifurcates the process of marshaling the payload and writing the http response
* replaces brittle `influxdb.marshalTimeseriesJSON*` funcs with struct tag-based marshaling
* fixes `marshal.go:248:5: ineffectual assignment to j (ineffassign)`
* removes the `r =` assignment in `r = r.WithContext(...)` whenever `r` is not used following the reassignment
* TODO's were added to track these, since they suggest a potential underlying defect that requires investigation
* fixes `SA4006: this value of `r` is never used (staticcheck)`
* Adds a `.WithResource` TracerProviderOption to OTLP Traces whenever Tags are …
> fix remaining lint issues

- pkg/proxy/engines/httpproxy.go
Looks like we are calling `mapLock.Lock()` twice here, and not unlocking. This looks like a mistake.
No coverage here, but I'll address that separately.
FYI, I spot checked other locks and didn't see this elsewhere.
> fix: [pkg/proxy] fix deadlock from double lock / missing  unlock

- .github/workflows/ci-build-tests.yml
- .gitignore
- Dockerfile
- Makefile
- hack/inspect-race-output.sh
- pkg/proxy/listener/listener_test.go
- pkg/timeseries/dataset/dataset.go
- pkg/timeseries/dataset/dataset_test.go
* Adds race detection test to CI workflow (but does not fail the CI job)
---
* Fixes a race condition provoked by test code in the `pkg/proxy/listener` package accessing the listener's inner map
<details>
<summary> Race Condition </summary>
```
WARNING: DATA RACE
Read at 0x00c000456660 by goroutine 50:
runtime.mapdelete_faststr()
/opt/homebrew/Cellar/go/1.24.1/libexec/src/internal/runtime/maps/runtime_faststr_swiss.go:396 +0x8c
github.com/trickstercache/trickster/v2/pkg/proxy/listener.TestListeners()
/Users/c/code/oss/trickster/pkg/proxy/listener/listener_test.go:69 +0x308
testing.tRunner()
/opt/homebrew/Cellar/go/1.24.1/libexec/src/testing/testing.go:1792 +0x180
testing.(*T).Run.gowrap1()
/opt/homebrew/Cellar/go/1.24.1/libexec/src/testing/testing.go:1851 +0x40
Previous write at …
```
> fix: [pkg/proxy/listener] [pkg/timeseries/dataset] fix data races

- Makefile
Fix release error that I hit validating the [release workflow](https://github.com/crandles/trickster/actions/runs/14037181355/job/39297955513):
```
/bin/sh: 1: pushd: not found
```
> fix: [ci] fix release workflow sha256sum generation

- hack/inspect-race-output.sh
- pkg/proxy/engines/cache.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/progressive_collapse_forwarder.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/request/resources.go
Fixing data races in `pkg/proxy`. (In conjunction with #743, this should bring us to zero races)
---
*  concurrent adds to a sync.waitgroup
* Fix: replaced with `sync.Cond` + int
<details>
<summary>Race Condition</summary>
```
WARNING: DATA RACE
Write at 0x00c000868028 by goroutine 10389:
runtime.racewrite()
<autogenerated>:1 +0x10
github.com/trickstercache/trickster/v2/pkg/proxy/engines.(*progressiveCollapseForwarder).WaitAllComplete()
/Users/c/code/oss/trickster/pkg/proxy/engines/progressive_collapse_forwarder.go:147 +0x3c
github.com/trickstercache/trickster/v2/pkg/proxy/engines.TestPCFWaits.func2()
/Users/c/code/oss/trickster/pkg/proxy/engines/progressive_collapse_forwarder_test.go:164 +0x44
Previous read at 0x00c000868028 by goroutine 10388:
runtime.raceread()
<autogenerated>:1 +0x10 …
```
> fix: [pkg/proxy] fix data races

- go.mod
- pkg/observability/logging/logging.go
- pkg/proxy/engines/cache.go
- pkg/timeseries/dataset/dataset_test.go
- pkg/timeseries/timeseries.go
fixes #756
The main cause of this is that the chunking aggregator was susceptible to a nil pointer panic if the first index of the cache chunk lookup in the results slice was a cache miss (meaning the chunk data is nil). This change ensures that nil chunk results (at any indexes) are removed from the results slice before performing the chunk aggregation.
This also properly logs errors in the partial cache chunk queries and properly handles cache miss and non-memory unmarshaling based on the lookup result.
This also bumps the go.mod toolchain to `go1.24.1` and fixes a logger issue where objects of type `error` or that conform to `fmt.Stringer` were not properly enclosing their stringified output in quotes when required.
> fix cache chunk panic

- .github/workflows/ci-build-tests.yml
- .github/workflows/publish-beta-release.yaml
- .github/workflows/publish-image.yaml
- .github/workflows/publish-release-candidate.yaml
- .github/workflows/publish-release.yml
- Dockerfile
- Makefile
- hack/release-sha256.sh
Did a bit of testing on my private fork, this _should_ have a better chance of succeeding.
* Publishes a docker image on tag
* Fixes bug found in initial run of `publish-image` workflow (https://github.com/trickstercache/trickster/actions/runs/14149543077)
* Refactors docker publishing to use the docker build-push action + use GHA cache
*  Refactors sha256sum generation to fix observed errors (`/bin/sh: 2: [[: not found`)
* Removes force rebuilding of standard library packages in release workflow (`-a`)
* Only builds for one architecture during PR workflows; we aren't doing anything platform specific
* Replaces to-be-deprecated `::set-output` usages
* Allow PR workflow to succeed in forked repositories (skip code coverage publishing)
* Cross compile trickster from local build platform -- …
> feat: [ci] add docker image release on "on tag" workflow & minor fixes

- .github/workflows/publish-image.yaml
- Dockerfile
- Makefile
Use the debian distroless image as the final stage.
```
docker image ls | grep trick
trickster           2.0.0-betaN                                159e48c7475d   4 minutes ago       27.7MB
```
Seems to work from what I can tell, but would welcome extra testing.
> feat: [docker] use distroless as final stage

- .github/workflows/publish-image.yaml
- .github/workflows/publish-release.yml
* Adds sbom & provenance attestation to the images publish workflow.
* Fixes minor permissions bug in workflow.
* Simplifies image versioning
---
branch + sha tags:
version tags:
rc/beta:
---
FYI, I verified the beta/release workflows work as expected.
Occasionally the create-release action hangs on an error; but I'm not sure why.
- https://github.com/trickstercache/trickster/blob/f405c963c65452ee1c6131e1d61c8df3c32854f2/.github/workflows/publish-release.yml#L61
- https://github.com/actions/create-release/issues/103
> feat: [docker] add sbom attestation and provenance to image publishing workflow

- pkg/cache/redis/cluster.go
- pkg/cache/redis/options/options.go
- pkg/cache/redis/sentinel.go
- pkg/cache/redis/standard.go
- pkg/config/types/doc.go
- pkg/config/types/envstring.go
- pkg/config/types/envstring_test.go
* Adds a new package `pkg/config/types` for common custom types used across the config / options structs
* Adds a new type `type EnvString` that automatically expands environment variable references as it is decoded from a config file
* Updates the redis password to use the new `EnvString` type
example:
```yaml
caches:
default:
redis:
password: "${MY_REDIS_PW}"
```
> feat: [redis/config] allow referencing redis password via env variable

- docs/alb.md
- docs/configuring.md
- docs/new-changed-2.0.md
- docs/paths.md
- pkg/backends/healthcheck/options/options.go
- pkg/config/types/envstring.go
- pkg/config/types/envstring_test.go
- pkg/proxy/headers/sensitive.go
- pkg/proxy/paths/options/options.go
Following #769, adds environment substitution support to the backend and health-check header values.
Adds new type, `type EnvStringMap map[string]string` to handle substitution into a map of values; this type is chosen so that it is more easily retrofit into the current `map[string]string` usage.
> feat: [config] allow referencing header values from environment variables

- pkg/proxy/tls/options/options.go
- pkg/router/lm/lm.go
- pkg/router/lm/lm_test.go
- pkg/timeseries/dataset/point.go
- pkg/timeseries/dataset/point_test.go
- pkg/util/strings/strings.go
- pkg/util/strings/strings_test.go
* Removes unused code
* Replaces custom string/slice functions with stdlib
* Removes extra `slices.reverse` call in `pkg/router/lm`
* Optimize point size calculation
---
Equal -- ~no change
Unique --  20% improvement
```
BenchmarkEqual-12     	245202459	         4.393 ns/op
BenchmarkUnique-12    	14429709	        88.49 ns/op
```
vs (main):
```
BenchmarkEqual-12     	263193535	         4.449 ns/op
BenchmarkUnique-12    	10249306	       112.2 ns/op
```
---
Points.Size -- looks like a big improvement -- I'm not sure if the goroutine was helping here
```
BenchmarkPointsSize-12    	     100	       654.5 ns/op
```
vs (main):
```
BenchmarkPointsSize-12    	     100	    291119 ns/op
```
> refactor: use more stdlib & optimize dataset/points.Size

- security-insights.yml
This PR adds a `security-insights.yml` file that conforms to the schema in https://github.com/ossf/security-insights-spec/releases/download/v2.0.0/schema.cue
This file and its data are added to add Trickster to the list of CNCF projects that have adopted the https://github.com/ossf/security-insights-spec?tab=readme-ov-file#security-insights-specification and is intended to help Trickster users easily discover and understand the security characteristics of the project.
> Add security-insights.yml to report security metadata

- pkg/backends/clickhouse/url.go
- pkg/proxy/headers/result_header.go
Minor improvement -- use a `strings.Replacer` instead of multiple `strings.Replace/ReplaceAll` calls.
> chore: use strings.Replacer

- Makefile
This adds a `check-license-headers` Makefile action that will fail (with instructions to fix) if any `.go` file is missing the project's License Header.  The action is run before `test` action to ensure that new PRs can't be accepted if files are added without the license header. The CI github action already runs `make test` to close the loop.
> add check-license-headers Makefile action

- pkg/timeseries/extent_list.go
- pkg/timeseries/extent_list_test.go
This flattens `ExtentList.CalculateDeltas` to use an `O(n + m)` merge-sweep in place of the `O(n²)` nested loops, while eliminating appends. It also removes a few appends from ExtentList's `Remove` and `Compress` functions. Optimizes a number of ExtentList functions for splicing, merging, cropping, cloning, and removing ExtentList data.
> improve extent list performance

- pkg/timeseries/epoch/epoch.go
- pkg/timeseries/epoch/epoch_gen.go
Address overflow concerns in `epoch.Epoch` usage by utilizing an int64 as the backing type.
~~I'm not sure if we were using uint64 for any particular reason, it wasn't obvious if so.~~ (Confirmed: no outside requirement)
We seem to utilize Epoch around `time.Time{}.UnixNano` which is int64.
Related: #785 (this reduces the number of reported issues from 37 -> 19)
> fix: address gosec G115 overflow potential in epoch.Epoch

- .golangci.yml
- Makefile
- examples/conf/example.full.yaml
- pkg/backends/influxdb/model/marshal.go
- pkg/backends/influxdb/model/unmarshal.go
- pkg/cache/badger/badger.go
- pkg/config/config.go
- pkg/config/tls.go
- pkg/daemon/setup/listeners.go
- pkg/frontend/options/defaults.go
- pkg/frontend/options/options.go
- pkg/frontend/options/options_test.go
- pkg/parsing/token/token_type.go
- pkg/proxy/listener/listener.go
- pkg/proxy/listener/listener_test.go
- pkg/proxy/proxy.go
- pkg/timeseries/dataset/series_header.go
- pkg/timeseries/dataset/series_header_gen.go
- pkg/timeseries/dataset/series_test.go
- pkg/util/middleware/simulated_latency.go
Adds gosec to golangci-lint and resolves all warnings.
Notable changes:
- the series header calculate hash func was changed to render an 8 byte hash
- adds a new frontend config -- `read_header_timeout`
- Re: `[CWE-400] Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (Rule:G112, Severity:MEDIUM, Confidence:LOW)` 
Resolves #785
-----
To Do:
- mainly: I wasn't sure whether to choose uint32 or uint64 for the timestampIndex size. How large can indexes be?
- If I change CalculateHash to support uint64, then more changes need to occur, as the hash needs to become larger. not sure if that's OK. 
- in retrospect: I forget that uint should generally default to uint64; that's probably the better choice to pick and simplifies this concern
> fix: add gosec to golangci-lint and resolve warnings

- pkg/backends/alb/first_response.go
- pkg/backends/clickhouse/model/model.go
- pkg/backends/influxdb/model/unmarshal.go
- pkg/backends/prometheus/model/timeseries.go
- pkg/backends/prometheus/model/timeseries_test.go
- pkg/cache/filesystem/filesystem.go
- pkg/cache/memory/memory.go
- pkg/proxy/engines/deltaproxycache.go
- pkg/proxy/engines/proxy_request.go
* Prefer adding to a waitgroup once instead of per loop item when we do not skip loop items.
* Fix bug in prometheus timeseries unmarshal code where points were likely to be out of order
> perf: make less WaitGroup.Add calls

- pkg/timeseries/dataset/tags.go
Remove an unnecessary mutex around tag merging that wasn't guarding anything, as far as I could tell.
> fix: remove extra mutex

- pkg/backends/influxdb/model/unmarshal.go
- pkg/backends/prometheus/model/timeseries.go
- Remove mutex usage when accessing distinct slice indexes
- Fix influxdb model -- it was still using the append pattern and could've been reordering points.
> perf: optimize prometheus and influx unmarshaling, slice access by index safe without mutex

- pkg/observability/logging/level/level.go
- pkg/observability/logging/level/level_test.go
- pkg/observability/logging/logging.go
- pkg/observability/logging/logging_test.go
Scanning the codebase for some simple performance gains -- here's a 5x speedup of log level ID conversion:
---
1. Removes a map lookup in favor of a simple type switch.
```console
BenchmarkGetLevelID-12    	549921196	         2.106 ns/op	       0 B/op	       0 allocs/op
```
vs main
```console
BenchmarkGetLevelID-12    	100000000	        11.45 ns/op	       0 B/op	       0 allocs/op
```
---
2. Replaces a mutex+map with sync.Map
(Only a minor improvement in overall runs / about the same ns/ops)
```console
Benchmark_logOnce-12    	 8518489	       149.9 ns/op	     336 B/op	       2 allocs/op
```
vs main
```console
Benchmark_logOnce-12    	 7707423	       143.7 ns/op	     336 B/op	       2 allocs/op
```
---
3. Reduce allocations in logging package / optimize keypair sorting
```console …
```
> perf: optimize logging package

- pkg/backends/alb/first_response.go
- pkg/backends/alb/responder_claim.go
Here's another mutex we can remove from the alb backend.
> perf: refactor the alb first responder claim to use atomics

- pkg/timeseries/dataset/dataset.go
Slice access by index is safe without a mutex.
> perf: remove mutex in dataset

- pkg/backends/healthcheck/healthcheck.go
- pkg/backends/healthcheck/healthcheck_test.go
- pkg/backends/healthcheck/target.go
- pkg/backends/healthcheck/target_test.go
- pkg/proxy/handlers/health/health.go
* Another mutex -> atomic change
* Refactoring code to use context for cancellation and remove some unnecessary logic
* removing context from a struct:
> Do not store Contexts inside a struct type
> https://pkg.go.dev/context#pkg-overview
> refactor:  rework backend and proxy health checks

- Makefile
- docs/developer/environment/README.md
- docs/developer/environment/docker-compose-data/grafana-config/provisioning/datasources/datasource.yaml
* Add the filesystem cache to the grafana dashboard.
* Fix readme Makefile target references
> docs: add filesystem cache datasource to grafana config

- pkg/backends/rule/parse.go
This resolves #677, which points out what looks to be a bug in the rules option parsing code.
`rmatch` is not an `InputType`, it is an `Operation`.
This is causing a panic and needs investigating.
> fix: [backend/rules] rmatch is operation not input type

- pkg/cache/index/client.go
- pkg/cache/index/client_test.go
- pkg/cache/manager/manager.go
- drop unused param
- omit log warning on index cache missing for memory client
> fix: omit index load warning for memory client

- .github/workflows/publish-image.yaml
- Dockerfile
- Makefile
The Dockerfile doesn't include the `.git` directory, so inject the tag version while building:
```
TAGVER=va.b.c make docker
docker run ...:va.b.c
...
time=2025-05-29T23:20:28.00332067Z app=trickster level=info event="application loaded from configuration" buildTime=2025-05-29T23:18:55+0000 commitID=9ddfa17cf6d5356a500f43682800218420fe5c7b config=/etc/trickster/trickster.yaml goArch=arm64 goOS=linux goVersion=go1.24.2 logLevel=INFO name=trickster pid=1 version=va.b.c
```
> fix: inject application version into dockerfile

- Makefile
- docs/developer/environment/README.md
- docs/developer/environment/docker-compose.yml
- pkg/backends/influxdb/flux/marshal_csv.go
- pkg/proxy/engines/cache.go
- pkg/proxy/response/merge/timeseries.go
- pkg/timeseries/dataset/series_header.go
- pkg/timeseries/dataset/series_list.go
- pkg/timeseries/timeseries.go
This fixes a few defects affecting the ALB Timeseries Merge mechanism, and  makes a few adjustments to the Developer Environment to help with general testing.
* Adds a `developer-stop` Makefile action that will stop the docker compose without destroying it
* Allows the `serve-dev` action to read a `TRK_CONFIG` environment variable to load an alternate config file (e.g., one crafted for specific test cases)
* Adds `restart: always` to containers in the Dev Env that needed it
* Fixes #845 by skipping over nil series when present
* Fixes #844 by ensuring that Series Header Hashes are recalculated before merging, in case they were altered since the hash was last calculated.
* unDRY merging a slice of Timeseries by consolidating into timeseries.List.Merge() everywhere.
> ALB and Timeseries Patches

- README.md
- docs/body.md
- examples/conf/example.full.yaml
- pkg/backends/alb/mech/fr/first_response.go
- pkg/backends/alb/mech/nlm/newest_last_modified.go
- pkg/backends/alb/mech/tsm/time_series_merge.go
- pkg/backends/options/defaults.go
- pkg/backends/prometheus/url.go
- pkg/backends/prometheus/url_test.go
- pkg/daemon/setup/setup.go
- pkg/frontend/options/defaults.go
- pkg/frontend/options/options.go
- pkg/frontend/options/options_test.go
- pkg/proxy/engines/key_test.go
- pkg/proxy/engines/proxy_request.go
- pkg/proxy/handlers/clickhouse/clickhouse.go
- pkg/proxy/handlers/influxdb/influxdb.go
- pkg/proxy/handlers/prometheus/prometheus.go
- pkg/proxy/handlers/rpc/rpc.go
- pkg/proxy/handlers/trickster/failures/failures.go
- pkg/proxy/request/body.go
- pkg/proxy/request/request.go
- pkg/proxy/request/resources.go
- pkg/proxy/response/merge/merge.go
- pkg/routing/routing.go
- pkg/routing/routing_test.go
- pkg/util/middleware/bodyfilter/bodyfilter.go
- pkg/util/middleware/bodymgr/bodymgr.go
- pkg/util/pointers/pointers.go
- pkg/util/pointers/pointers_test.go
This patch fixes #808 and #806 by centralizing reading of the request body to a middleware handler that also implements the size limiter using an `io.LimitReader` as part of the centralized read. The default max request body size is 10MB but can be udpated in the config yaml. This patch also addresses POST-related defects in the ALB due to incompatibilities between the various non-centralized, slightly different DRY body reading implementations that are now refactored.
> add Request Body Size Limiter

- pkg/backends/prometheus/model/model.go
- pkg/backends/prometheus/model/timeseries.go
- pkg/proxy/request/resources.go
This patch allows Trickster to support Scalar responses from a Prometheus server. While not generally used by end users, Scalar responses are used by certain health check agents (e.g., the Grafana Datasource tester); so this ensures those check can pass as expected instead of producing an unmarshaling error.
> support scalar responses

- pkg/config/validate/validate.go
- pkg/daemon/daemon.go
- pkg/daemon/setup/listeners.go
- pkg/daemon/setup/setup.go
- pkg/observability/pprof/pprof.go
- pkg/observability/pprof/pprof_test.go
- pkg/routing/routing.go
- pkg/routing/routing_test.go
This PR fixes a panic when using `rule` backends. Fixes #856. The root cause of the panics was due to a change between Beta1 and Beta2 in the ordering of how configurations are loaded and when the http clients for the configured backends are instantiated.
To fix this, the scoping of the instantiated backend clients lookup has been moved into the `daemon` package and is now passed around and shared between the 'dryRun' (validation) setup and the actual running config setup, instead of being instantiated twice (once in validation and once in actual).
Separately, the Pprof routes instantiation has been moved to its own package for separation of concerns.
Ultimately, more streamlining and refinement is needed for this part of the codebase, but since it's generally working we can probably …
> fix rules panic

- docs/caches.md
- docs/chunked_caching.md
- docs/new-changed-2.0.md
- docs/roadmap.md
Update documentation for Rules, Redis (TLS), Whats New and Roadmap. Simplify Cache Chunking example YAML.
> docs update
